[phases.setup]
nixPkgs = ["...", "php82", "nginx"] # Remplacez php82 par votre version de PHP si besoin

[phases.build]
cmds = ["echo 'Configuration terminée'"]

[start]
cmd = "nginx -g 'daemon off;' -c /app/nginx.conf"